<?php

namespace GER\Bundle\AmazonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecordSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordSetRepository extends EntityRepository
{
}
