GER\Bundle\AmazonBundle\Entity\RecordSet:
    type: entity
    table: domains_recordsets
    repositoryClass: GER\Bundle\AmazonBundle\Entity\RecordSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ttl:
            type: integer
        name:
            type: string
            length: 255
        value:
            type: text
    lifecycleCallbacks: {  }
